### ISSUE TITLE
gmongo 0.9 is compiled with Groovy 1.8 causing errors with Groovy 1.7

### ISSUE THREAD

**Issue by graemerocher** [poiati/gmongo#6]
See http://hudson.grails.org/view/All/job/grails_data_mapping/lastCompletedBuild/testReport/org.grails.datastore.gorm.mongo/OneToOneIntegritySpec/Test_persist_and_retrieve_one_to_one_with_inverse_key/

The error is:

java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/BytecodeInterface8
    at com.gmongo.internal.Patcher._convert(Patcher.groovy:64)
    at com.gmongo.internal.Patcher._patchInternal_closure1(Patcher.groovy:32)

If you compile with Groovy 1.7 then it should be able to run in both 1.7 and 1.8 but if you compile with 1.8 it won't run in Groovy 1.7.

Could gmongo be updated to compile with 1.7 please?
